from __future__ import annotations


STEP_LABELS = {
    "raw_binding": "绑定 raw",
    "source_digest": "来源消化",
    "candidate_pages_warmup": "候选页缓存预热",
    "wiki_snapshot": "Wiki 快照",
    "candidate_pages": "候选知识页",
    "candidate_contexts": "候选召回",
    "merge_plan": "合并计划",
    "composition_plan": "写作编排",
    "final_pages": "最终页面",
    "coverage_judge": "覆盖审查",
    "related_refresh": "刷新相关页面",
    "validation": "校验",
    "knowledge_write": "写入知识页",
    "source_record_write": "写入来源页",
    "embedding_cache_refresh": "刷新向量缓存",
    "related_maintenance": "维护相关页面",
    "index_log_write": "写入索引日志",
    "receipt": "写入回执",
}

COUNT_LABELS = {
    "raw_size_bytes": "raw大小",
    "content_unit_count": "内容单元数",
    "warmup_count": "预热数",
    "skipped_content_unit_count": "跳过内容单元数",
    "weak_noise_count": "弱/噪声数",
    "granularity_effective_chars": "有效字数",
    "granularity_suggested_min_candidate_pages": "建议最少候选页",
    "granularity_suggested_target_candidate_pages": "建议目标候选页",
    "granularity_suggested_max_candidate_pages": "建议最多候选页",
    "knowledge_pool_size": "知识池",
    "candidate_page_count": "候选页数",
    "covered_content_unit_count": "覆盖内容单元数",
    "query_count": "查询数",
    "top_k": "TopK",
    "create_count": "新建数",
    "update_count": "更新数",
    "noop_count": "不改动数",
    "merge_decision_count": "合并决策数",
    "related_kept_count": "相关保留数",
    "related_filtered_count": "相关过滤数",
    "related_link_count": "相关链接数",
    "related_threshold": "相关阈值",
    "related_replacement_margin": "相关替换分差",
    "related_maintenance_checked_count": "相关维护检查数",
    "related_maintenance_written_count": "相关维护写入数",
    "related_maintenance_added_count": "相关维护新增数",
    "related_maintenance_replaced_count": "相关维护替换数",
    "related_maintenance_removed_count": "相关维护移除数",
    "body_link_count": "正文链接数",
    "final_target_count": "最终目标数",
    "final_page_count": "最终页数",
    "update_target_count": "更新目标数",
    "diff_count": "diff数",
    "preimage_coverage_requirement_count": "旧页覆盖要求",
    "preimage_coverage_report_count": "旧页覆盖报告",
    "claim_count": "知识点数",
    "covered_claim_count": "已覆盖知识点",
    "partial_claim_count": "部分覆盖知识点",
    "missing_claim_count": "缺失知识点",
    "contradicted_claim_count": "冲突知识点",
    "core_claim_count": "核心知识点",
    "core_missing_claim_count": "核心缺失知识点",
    "raw_claim_coverage_percent": "知识覆盖率",
    "core_claim_coverage_percent": "核心覆盖率",
    "concept_coverage_percent": "概念覆盖率",
    "coverage_repair_count": "覆盖修复次数",
    "coverage_repair_final_page_count": "覆盖修复页数",
    "claim_repair_count": "claim修复次数",
    "claim_repair_claim_count": "claim修复数",
    "parallel_request_count": "并发请求",
    "parallel_max_workers": "最大并发",
    "error_count": "错误数",
    "warning_count": "警告数",
    "artifact_count": "产物数",
    "model_calls": "模型调用",
    "repair_count": "修复数",
    "semantic_retry_count": "语义重试数",
    "api_call_count": "API调用",
    "api_success_count": "API成功",
    "api_paused_count": "API暂停",
    "prompt_tokens": "输入token",
    "prompt_cache_hit_tokens": "命中缓存token",
    "prompt_cache_miss_tokens": "未命中缓存token",
    "completion_tokens": "输出token",
    "reasoning_tokens": "思考token",
    "total_tokens": "总token",
    "cache_hit_rate_percent": "缓存命中率",
    "price_cny": "价格",
    "knowledge_written_count": "知识页写入数",
    "source_record_count": "来源页数",
    "system_written_count": "系统页数",
    "written_target_count": "写入目标数",
    "receipt_count": "回执数",
    "cache_hit": "缓存命中",
    "cache_refreshed": "缓存刷新",
    "cache_pruned": "缓存清理",
    "retrieval_backend": "召回后端",
}


def step_label(name: str) -> str:
    return STEP_LABELS.get(name, name)


def count_label(key: str) -> str:
    return COUNT_LABELS.get(key, key)
